# Generated by Django 4.1.7 on 2023-08-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sale_man",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="node_visitors",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
