# Generated by Django 4.1.7 on 2023-03-31 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_delete_lights"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lights",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.product",
                    ),
                ),
                ("product_number", models.CharField(max_length=50)),
                ("watt", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Lights",
            },
            bases=("core.product",),
        ),
    ]
