# Generated by Django 4.1.7 on 2023-08-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_categories_id_alter_company_name_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
