# Generated by Django 4.1.7 on 2023-05-12 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_order_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="products",
            new_name="products_list",
        ),
    ]
