# Generated by Django 4.1.7 on 2023-05-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_products_order_products_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
    ]
