# Generated by Django 4.1.7 on 2023-08-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_order_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
