# Generated by Django 4.1.7 on 2023-05-15 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_order_ordered"),
    ]

    operations = [
        migrations.CreateModel(
            name="showroom_settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("android_app_link", models.CharField(default="#", max_length=250)),
                ("ios_app_link", models.CharField(default="#", max_length=250)),
                ("facebook", models.CharField(default="#", max_length=50)),
                ("instagram", models.CharField(default="#", max_length=50)),
                ("twitter", models.CharField(default="#", max_length=50)),
                (
                    "showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.showrooms"
                    ),
                ),
            ],
        ),
    ]
