# Generated by Django 4.1.7 on 2023-03-31 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_tiles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tiles",
            old_name="sixe",
            new_name="size",
        ),
    ]
