# Generated by Django 4.1.7 on 2023-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_order_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
