# Generated by Django 4.1.7 on 2023-03-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_sixe_tiles_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.product",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("car_model", models.CharField(max_length=50)),
                ("manufacturing_year", models.CharField(max_length=50)),
                ("registration_year", models.CharField(max_length=50)),
                ("import_year", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Cars",
            },
            bases=("core.product",),
        ),
    ]
