# Generated by Django 4.1.7 on 2023-05-16 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_showroom_settings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="completed",
            new_name="delivered",
        ),
    ]
