# Generated by Django 4.1.7 on 2023-05-17 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_completed_order_delivered"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="approved",
            new_name="accepted",
        ),
    ]
