# Generated by Django 4.1.7 on 2023-03-31 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_cars"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sanitary_Ware",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.product",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Sanitary Ware",
            },
            bases=("core.product",),
        ),
        migrations.RenameField(
            model_name="cars",
            old_name="car_model",
            new_name="model",
        ),
    ]
