# Generated by Django 4.1.7 on 2023-05-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_approved_order_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
