# Generated by Django 4.1.7 on 2023-05-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_order_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="showroom_settings",
            name="shop_logo",
            field=models.ImageField(
                blank=True,
                default="default_shop_logo.png",
                null=True,
                upload_to="shop_logo",
            ),
        ),
        migrations.AlterField(
            model_name="showroom_settings",
            name="address",
            field=models.CharField(
                blank=True,
                default="Set your address in shop settings",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="showroom_settings",
            name="email",
            field=models.CharField(
                blank=True,
                default="Set your email in shop settings",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="showroom_settings",
            name="phone",
            field=models.CharField(
                blank=True,
                default="Set your phone in shop settings",
                max_length=50,
                null=True,
            ),
        ),
    ]
