# Generated by Django 4.1.7 on 2023-03-31 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_chip_board"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marble_Stone",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.product",
                    ),
                ),
                ("product_number", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Marble Stone",
            },
            bases=("core.product",),
        ),
    ]
