# Generated by Django 4.1.7 on 2023-05-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_showroom_settings_shop_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroom_settings",
            name="shop_logo",
            field=models.ImageField(
                blank=True,
                default="shop_logo/default_shop_logo.png",
                null=True,
                upload_to="shop_logo",
            ),
        ),
    ]
