# Generated by Django 4.1.7 on 2023-05-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_showroom_settings_shop_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroom_settings",
            name="shop_logo",
            field=models.ImageField(
                blank=True,
                default="static/shop_logo/default_shop_logo.png",
                null=True,
                upload_to="shop_logo",
            ),
        ),
    ]
