# Generated by Django 4.1.7 on 2023-04-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_marble_stone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sanitary",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.product",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("set", "set"), ("accessories", "accessories")],
                        max_length=50,
                    ),
                ),
                (
                    "accessories_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "set_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gold series", "gold series"),
                            ("silver series", "silver series"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("finshing", models.CharField(max_length=50)),
                ("style", models.CharField(max_length=50)),
                ("product_number", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Sanitary",
            },
            bases=("core.product",),
        ),
    ]
