# Generated by Django 4.1.7 on 2023-04-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_sanitary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Art_And_Culture",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.product",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("handmade", "handmade"),
                            ("machinemade", "machinemade"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "accessories_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("product_number", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
                ("weight", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name_plural": "Art And Culture",
            },
            bases=("core.product",),
        ),
    ]
