# Generated by Django 4.1.7 on 2023-04-01 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_art_and_culture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="art_and_culture",
            name="accessories_name",
        ),
    ]
