# Generated by Django 4.1.7 on 2023-05-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_transaction_shipping_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="shipping_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
