# Generated by Django 4.1.7 on 2023-04-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
