# Generated by Django 4.1.7 on 2023-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_cart_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product_quantity",
            field=models.IntegerField(default=1),
        ),
    ]
