# Generated by Django 4.1.7 on 2023-05-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(default="PENDING", max_length=10),
        ),
    ]
