# Generated by Django 4.1.7 on 2023-06-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="showrooms",
            name="google_analytics_link",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
